export const FETCH_FACULTY = "FETCH_FACULTY";
export const FETCH_FACULTY_START = "FETCH_FACULTY_START";
export const FETCH_FACULTY_SUCCESS = "FETCH_FACULTY_SUCCESS";
export const FETCH_FACULTY_FAIL = "FETCH_FACULTY_FAIL";