export const FETCH_UNIVERSITY = "FETCH_UNIVERSITY";
export const FETCH_UNIVERSITY_START = "FETCH_UNIVERSITY_START";
export const FETCH_UNIVERSITY_SUCCESS = "FETCH_UNIVERSITY_SUCCESS";
export const FETCH_UNIVERSITY_FAIL = "FETCH_UNIVERSITY_FAIL";