export const FETCH_PROGRAM = "FETCH_PROGRAM";
export const FETCH_PROGRAM_START = "FETCH_PROGRAM_START";
export const FETCH_PROGRAM_SUCCESS = "FETCH_PROGRAM_SUCCESS";
export const FETCH_PROGRAM_FAIL = "FETCH_PROGRAM_FAIL";