export const FETCH_TESTIMONI = "FETCH_TESTIMONI";
export const FETCH_TESTIMONI_START = "FETCH_TESTIMONI_START";
export const FETCH_TESTIMONI_SUCCESS = "FETCH_TESTIMONI_SUCCESS";
export const FETCH_TESTIMONI_FAIL = "FETCH_TESTIMONI_FAIL";